### ISSUE TITLE
Can not disable tasks with "is defined" condition

### ISSUE THREAD

**Issue by gw0** [MVladislav/ansible-docker#2]
### Describe the problem

All variables are defined in `defaults/main.yml` and some tasks have the `is defined` condition. In Ansible it is impossible to undefine a variable once it has been set, therefore these conditions do not make sense. E.g.

```py
  when:
    - docker_pip_dependencies is defined
```
- https://github.com/MVladislav/ansible-docker/blob/main/tasks/section0.yml#L32
- https://github.com/MVladislav/ansible-docker/blob/main/tasks/section0.yml#L124

I guess it would make most sense to just change this conditions to check if it is not empty (this covers not defined, not None, and not zero length). E.g.:

```py
  when:
    - docker_pip_dependencies
```

The code would become shorter and there would be multiple ways to disable it (e.g. set to `None` or set to empty list `[]` or empty string `""`...).

### Expected behavior

One would expect that Pip would be disabled with current defaults:

```py
docker_pip_dependencies: []
docker_install_pip: []
```
- https://github.com/MVladislav/ansible-docker/blob/main/defaults/main.yml#L20
- https://github.com/MVladislav/ansible-docker/blob/main/defaults/main.yml#L38

### What is version of application which has the issue?

ansible-docker

### What type of installation are you running?

OS (setup.py)

### What type of device you use to interact with the application?

OS: [e.g. linux, windows, ios]

**Comment by gw0** [comment]
I still believe that all `when:` blocks with the `is defined` condition actually want to check "is not empty" (meaning either not defined, None or length=0). To check for "is not empty" the `is defined` part just needs to be removed.

**Comment by gw0** [comment]
...

**Comment by MVladislav** [comment]
Hay @gw0 
thanks for your proposal, i will perform the changes next time (also saw this problem in other Ansible project i wrote)

and sorry for the auto bot stale comments, had not saw your issue and was busy the last months.

**Comment by MVladislav** [comment]
unset for list variables seams not be possible to set with 'null', loop runs before when.
but i add more checks to skip list variables when they are set as empty (with []).

if something missed or you have any other solution, let me know.
